import { Composition } from "remotion";
import { videoConf } from "../config/scenes";

import { All } from "./All";

import { calcMetadata } from "./calc-metadata";

export const Root = () => {
  return (
    <>
      <Composition
        component={All}
        id="augustupdate"
        schema={videoConf}
        defaultProps={{
          theme: "light",
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "soft" as const,
            },
            {
              type: "remotionupdate" as const,
              durationInFrames: 100,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Next.js template",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Image sequences",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Stills to clipboard",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Title bar progress",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "getRemotionEnvironment()",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "getSilentParts()",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Get codec and colorspace",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "x264 presets",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Auto-install Chrome",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Custom webhook data",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
              newChapter: "Lambda tutorial",
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "epic" as const,
              newChapter: "Cloud Run update",
              stopChapteringAfterThis: true,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              music: "previous" as const,
            },
            {
              type: "endcard" as const,
              durationInFrames: 200,
              music: "previous" as const,
              channel: "remotion" as const,
              platform: "x" as const,
              links: [],
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />
      <Composition
        component={All}
        id="test"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "title" as const,
              title: "My Test Video",
              subtitle: "Subtitle ",
              durationInFrames: 50,
              music: "none" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: 323,
              transitionToNextScene: true,
              newChapter: "Chapter 1",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />
      <Composition
        component={All}
        id="timing"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 60,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 33,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 55,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 30,
              duration: 1641,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 30,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 45,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 30,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 40,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 40,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 30,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 35,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 90,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 100,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 30,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "endcard" as const,
              durationInFrames: 200,
              music: "previous" as const,
              channel: "remotion" as const,
              platform: "youtube" as const,
              links: [{ link: "JonnyBurger/timing-functions" }],
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />
      <Composition
        component={All}
        id="january"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "landscape" as const,
          scenes: [
            {
              type: "remotionupdate" as const,
              music: "previous" as const,
              durationInFrames: 100,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Deployable Studio",
              stopChapteringAfterThis: false,
              music: "none" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "makeTransform()",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "interpolateStyles()",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "fitText()",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Better GIFs",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "New transitions",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Better Props editor",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Better timeline",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "HDR videos",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "--repro",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Jump to frame",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Open GitHub",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Beep on finish",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Measure elements",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "Remotion.pro Update",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: 1314,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: true,
              music: "previous" as const,
            },
            {
              type: "endcard" as const,
              durationInFrames: 200,
              music: "soft" as const,
              channel: "remotion" as const,
              platform: "youtube" as const,
              links: [],
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />{" "}
      <Composition
        component={All}
        id="pirates"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 33,
              duration: 691,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 33,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 65,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 45,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 42,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 120,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 90,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 40,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-right" as const,
              trimStart: 35,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-left" as const,
              trimStart: 30,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 45,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 65,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 65,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "endcard" as const,
              durationInFrames: 200,
              music: "soft" as const,
              channel: "jonny" as const,
              platform: "x" as const,
              links: [{ link: "remotion.dev/license" }],
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />{" "}
      <Composition
        component={All}
        id="bunbun"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 45,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: 956,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 42,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 38,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 54,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "endcard" as const,
              durationInFrames: 200,
              music: "soft" as const,
              channel: "jonny" as const,
              platform: "x" as const,
              links: [],
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />{" "}
      <Composition
        component={All}
        id="tiktok"
        schema={videoConf}
        defaultProps={{
          theme: "light" as const,
          canvasLayout: "square" as const,
          scenes: [
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 40,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-left" as const,
              trimStart: 30,
              duration: 159,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 52,
              duration: null,
              transitionToNextScene: false,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "top-right" as const,
              trimStart: 40,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "bottom-right" as const,
              trimStart: 0,
              duration: null,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
            {
              type: "videoscene" as const,
              webcamPosition: "previous" as const,
              trimStart: 0,
              duration: 830,
              transitionToNextScene: true,
              newChapter: "",
              stopChapteringAfterThis: false,
              music: "previous" as const,
            },
          ],
          scenesAndMetadata: [],
        }}
        calculateMetadata={calcMetadata}
      />
    </>
  );
};
